# Generated by Django 5.0.4 on 2024-05-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0003_course_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
