# Generated by Django 5.0.6 on 2024-06-11 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_parcels', to=settings.AUTH_USER_MODEL),
        ),
    ]
