# Generated by Django 5.0.6 on 2024-06-11 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_alter_parcel_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
