# Generated by Django 5.0.6 on 2024-06-11 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_alter_parcel_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryproof',
            name='parcel',
        ),
        migrations.AddField(
            model_name='parcel',
            name='delivery_proof',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courier.deliveryproof'),
        ),
        migrations.AlterField(
            model_name='deliveryproof',
            name='image',
            field=models.ImageField(upload_to='delivery_proofs/'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
