# Generated by Django 5.0.4 on 2024-04-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='redirections',
            field=models.IntegerField(default=0),
        ),
    ]
